---
# THIS IS SPECIFIC FOR REFELT - JUST TO GET A REFELT REGISTERED
# GENERALISATION OF CONFIG AND FOR OTHER ELEMENTS IS TBD

###########################################
##     PRINT STUFF
###########################################


- name: Print my hostvars
  debug:
      msg="{{item}}"
  with_items:
      - "hostvars[{{ inventory_hostname }}] = {{ hostvars[inventory_hostname] }}"

- name: Print vars
  debug:
      msg={{item}}
  with_items:
      - "software_root = {{ software_root }}"
      - "ansible_distribution = {{ ansible_distribution }}"
      - "ansible_hostname = {{ ansible_hostname }}"
      - "ansible_nodename = {{ ansible_nodename }}"
      - "inventory_hostname = {{ inventory_hostname }}"
      - "hostvars[{{ inventory_hostname }}].group_names = {{ hostvars[inventory_hostname].group_names }}"
      - "hostvars[{{ inventory_hostname }}].element_details = {{ hostvars[inventory_hostname].element_details }}"
      - "element_details.type = {{ hostvars[inventory_hostname].element_details.type }}"
      - "element_details.name = {{ hostvars[inventory_hostname].element_details.name }}"
      - "element_details.id = {{ hostvars[inventory_hostname].element_details.id }}"
  tags:
    - register-myrefelt-prints


- name: Extract my vars
  set_fact:
    my_element_details: "{{ hostvars[inventory_hostname].element_details }}"
    my_groups: "{{ hostvars[inventory_hostname].group_names }}"
    my_name: "{{ hostvars[inventory_hostname].element_details.name }}"
    my_id: "{{ hostvars[inventory_hostname].element_details.id }}"
    my_instance: "{{ hostvars[inventory_hostname].element_details.instance }}"
  tags:
    - register-myrefelt-prints

- name: Print my vars
  debug:
      msg="{{item}}"
  with_items:
      - "my_element_details = {{ my_element_details }}"
      - "my_name = {{ my_name }}"
      - "my_id = {{ my_id }}"
      - "my_instance = {{ my_instance }}"
      - "my_groups = {{ my_groups }}"
  tags:
    - register-myrefelt-prints



###########################################
##     Register in TANGO db
###########################################


- block:

  - name: Register MyRefElt servers, classes, devices in TANGO db
    vars:
        my_id : "{{ hostvars[inventory_hostname].element_details.id }}"
        # NOTE - the space before the double open curly brackets " {{..." is required
        # else ansible template processing replaces the double quotes with single qoutes
        # breaking the json
        # https://stackoverflow.com/questions/41144922/ansible-passing-json-string-in-environment-to-shell-module
        var_config_db: " {{ lookup('template', '{{ software_root }}/levpro/ansible/inventories/{{ my_name }}/config_files/config_db.json.j2') | to_json }}"
    register_element:
        config_json: "{{ var_config_db }}"
    register: the_result

  - name: Register MyRefElt device properties in TANGO db
    vars:
        # NOTE - the space before the double open curly brackets " {{..." is required - see above
        var_config_properties: " {{ lookup('template', '{{ software_root}}/levpro/ansible/inventories/{{my_name}}/config_files/config_properties.json.j2') | to_json }}"
    register_properties:
        properties_json: "{{ var_config_properties }}"
    register: the_result

  tags:
    - register-myrefelt-in-tangodb

###########################################
###     Register in ASTOR
############################################
- block:
  - name: Set StartDsPath
    set_starter_ds_path:
      starter_path="/usr/local/bin/"
    register: the_result
  tags:
    - register-myrefelt-in-astor
    - register-myrefelt-in-astor-ds-path

- block:
  - name: Register MyRefElt in Astor and restart with Starter
    vars:
        # NOTE - the space before the double open curly brackets " {{..." is required - see above
        var_config_starter: " {{ lookup('template', '{{ software_root }}/levpro/ansible/inventories/{{ my_name }}/config_files/config_starter.json.j2') | to_json }}"
    start_element:
      starter_json: "{{ var_config_starter }}"
    register: the_result
  tags:
    - register-myrefelt-in-astor
...
