---

###########################################
## PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"

###########################################
## Apt-get update and upgrade
###########################################

- name: update apt packages
  apt: >
    update_cache=yes
    cache_valid_time=3600

#################################
# Install deb packages
#################################

- name: Install deb requirements packages
  apt: name={{item}} force=yes state=latest
  with_items:
    - aptitude
    - libffi-dev
    - build-essential
    - git-core
    - language-pack-en-base
    - libatk1.0-dev
    - libcairo2-dev
    - libevent-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libpng12-dev
    - libpq-dev
    - python-cairo-dev
    - python-dev
    - libboost-python-dev
    - gfortran
    - screen
    - zlib1g-dev
    - tzdata
    - ntpdate
    - liblapack-dev
    - libf2c2-dev
    - libatlas-base-dev
    - libssl0.9.8
    - man-db
    - manpages
    - ftp
    - gawk
    - telnet
    - tcpdump
  tags:
    - debs
    - deploy-tangobox-debs

#################################
# Install mysql
#################################

- name: Check if MySQL is already installed.
  stat: path="/etc/init.d/mysql"
  register: mysql_installed
  tags:
    - mysql
    - deploy-tangobox-mysql
    - deploy-tangobox-mysql-installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes cache_valid_time=3600
  when: mysql_installed.stat.exists == false
  tags:
    - mysql
    - deploy-tangobox-mysql
    - deploy-tangobox-mysql-installed

- name: Install mysql packages
  apt: name={{item}} state=installed
  #ignore_errors: yes
  when: mysql_installed.stat.exists == false
  with_items:
    - software-properties-common
    - mysql-client-core-5.6
    - mysql-server-5.6
    - mysql-client-5.6
  tags:
    - mysql
    - deploy-tangobox-mysql

#################################
# Install core tango debs
#################################

- apt_key:
    id: 5AD0CC81421C3A8B
    keyserver: keyserver.ubuntu.com
  tags:
    - tango-core
    - deploy-tangobox-tango-core

- apt_repository:
    repo: deb http://ppa.launchpad.net/lmc-cam-ska/tango/ubuntu trusty main
    state: present
    update_cache: yes
  tags:
    - tango-core
    - deploy-tangobox-tango-core

- name: Install tango core packages
  apt:
    name={{item}} force=yes state=latest
  with_items:
    - tango-db
    - tango-common
    - tango-starter
    - tango-test
    - tango-accesscontrol
    - liblog4tango5v5
    - libtango9
    - libtango-doc
    - libtango-dev
    - liblog4tango-dev
    - liblog4tango-doc
  tags:
    - tango-core
    - deploy-tangobox-tango-core

###############################################
# Install tango java tools like pogo and jive
###############################################

- name: Check if libtango-java is already installed
  command: dpkg-query -W libtango-java
  register: libtango_java_installed
  failed_when: libtango_java_installed.rc > 1
  changed_when: libtango_java_installed.rc == 1
  tags:
    - tango-java
    - deploy-box-tango-java

- name: Install libtango-java if not already installed
  apt:
    deb: https://people.debian.org/~picca/libtango-java_9.2.5a-1_all.deb
  when: libtango_java_installed.rc == 1
  tags:
    - tango-java
    - deploy-tangobox-tango-java

#################################
# Pip install tango packages
#################################

- name: Pip install tango packages
  pip: name={{item}}
  with_items:
    - numpy
    - ipython<6.0
    - fandango
    - PyTango
  tags:
    - pip
    - deploy-tangobox-pip

#################################
# Pip install itango separately
#################################

- name: Install itango and tango-admin pip packages - no-deps
  # Use no-deps as it was trying to install IPython > 6.0
  # which is not compatible with Python 2.6/2.7
  pip: name={{ item }} extra_args="-U --no-deps"
  with_items:
    - tango-admin
    - six>=1.9.0  # itango requirement
    - itango
  tags:
    - itango
    - deploy-tangobox-itango


#################################
# Start Tango DB
#################################

- name: ensure that tangodb is running
  service: name=tango-db state=started
  tags:
    - deploy-tangobox-start-tango

################################
# Include Tango Webapp role
################################
- include: tango_webapp.yml
...
