---
# STOP AND DEREGISTER ALL SERVERS STARTING WITH SvrRef

###########################################
##     PRINT STUFF
###########################################

- name: Print software_root directory
  debug: msg="rootdir = {{software_root}}"


###########################################
##     Register in TANGO db
###########################################

- block:
  - name: Deregister RefElt servers, classes, devices
    deregister_selected_servers:
      do_what: "delete_servers"
      startswith: "SvrRef,SKALogger"
  tags:
    - deregister-refelts-delete-in-tangodb

###########################################
###     Stop in ASTOR
############################################

- block:
  - name: Stop all servers starting with SvrRef in Astor
    deregister_selected_servers:
      do_what: "stop_servers"
      startswith: "SvrRef,SKALogger"
  tags:
    - deregister-refelts-stop-in-astor
...
